<a href="https://colab.research.google.com/github/Jahid11186/NumpyPandas-101/blob/main/Numpy/Numpy_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy**

Numpy - Numerical Python

In [ ]:
import numpy as np

In [ ]:
# 1-D Array
d = np.array([1, 2, 3, 4])
d

array([1, 2, 3, 4])

In [ ]:
type(d)

numpy.ndarray

In [ ]:
# Multi Dimentional Array
md = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
type(md)

numpy.ndarray

In [ ]:
md

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
md.shape

(4, 3)

In [ ]:
md.dtype

dtype('int64')

In [ ]:
d.shape

(4,)

### Zero matrix

In [ ]:
z = np.zeros(3)
z

array([0., 0., 0.])

In [ ]:
mz = np.zeros([3, 4])
mz

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Diagonal Matrix

In [ ]:
e = np.eye(3)
e

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
e2 = e + 2
e2

array([[3., 2., 2.],
       [2., 3., 2.],
       [2., 2., 3.]])

In [ ]:
# create an unit matrix like the size of 'md'
u = np.ones_like(e2)
u

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
u.dtype

dtype('float64')

In [ ]:
ui = u.astype(np.int32)
ui

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [ ]:
ui.dtype

dtype('int32')

### Convert string list to float

In [ ]:
a = ['1', '2', '3']
a_arr = np.array(a, dtype=np.string_) # convert list to ndarray
af = a_arr.astype(float)
af

array([1., 2., 3.])

In [ ]:
af.dtype

dtype('float64')

### Boolean Indexing

In [ ]:
data = np.random.randn(5, 3)
data

array([[-1.83584178, -1.35240228,  0.61936011],
       [ 2.43988546,  0.89642254, -1.24807216],
       [-2.08065537, -0.00876089, -0.44897702],
       [-0.2710115 ,  0.24444758, -0.9506376 ],
       [-1.31888425,  0.4929659 , -0.88708124]])

In [ ]:
name = np.array(['a', 'b', 'c', 'a', 'b'])
name == 'a'

array([ True, False, False,  True, False])

In [ ]:
name != 'a'

array([False,  True,  True, False,  True])

In [ ]:
data[name=='a']

array([[-1.83584178, -1.35240228,  0.61936011],
       [-0.2710115 ,  0.24444758, -0.9506376 ]])

In [ ]:
data[name!='a']

array([[ 2.43988546,  0.89642254, -1.24807216],
       [-2.08065537, -0.00876089, -0.44897702],
       [-1.31888425,  0.4929659 , -0.88708124]])

In [ ]:
name == 'c'
name

array(['a', 'b', 'c', 'a', 'b'], dtype='<U1')

In [ ]:
data[name=='c']

array([[-2.08065537, -0.00876089, -0.44897702]])

In [ ]:
data[name == '1']

array([], shape=(0, 3), dtype=float64)

In [ ]:
data[(data > 1) & (data < 2)]

array([], dtype=float64)

### Reshaping Arrays

In [ ]:
a = np.arange(0, 20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
a45 = a.reshape(4, 5)
a45

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
a102 = a.reshape(10, 2)
a102

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [ ]:
b = a45[[2, 0, 1]]
b

array([[10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9]])

In [ ]:
# Transpose array b
b.T

array([[10,  0,  5],
       [11,  1,  6],
       [12,  2,  7],
       [13,  3,  8],
       [14,  4,  9]])

### Concatenating the data

In [ ]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
rn = np.random.randn(3,4)
rn

array([[ 0.45243317,  0.1525085 ,  1.6075183 ,  1.20181243],
       [ 0.52563117, -1.02840951,  0.68786167, -0.49881484],
       [-1.20474781,  1.1291907 ,  0.71946662,  0.90291726]])

In [ ]:
np.concatenate([arr, rn])

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.45243317,  0.1525085 ,  1.6075183 ,  1.20181243],
       [ 0.52563117, -1.02840951,  0.68786167, -0.49881484],
       [-1.20474781,  1.1291907 ,  0.71946662,  0.90291726]])

In [ ]:
np.concatenate([rn, arr], axis=1)

array([[ 0.45243317,  0.1525085 ,  1.6075183 ,  1.20181243,  0.        ,
         1.        ,  2.        ,  3.        ],
       [ 0.52563117, -1.02840951,  0.68786167, -0.49881484,  4.        ,
         5.        ,  6.        ,  7.        ],
       [-1.20474781,  1.1291907 ,  0.71946662,  0.90291726,  8.        ,
         9.        , 10.        , 11.        ]])